In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn import metrics
import re
import string

In [2]:
fake_news=pd.read_csv("Fake1.csv")
true_news=pd.read_csv("True1.csv")

In [3]:
fake_news.head(10)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   
5  The number of cases of cops brutalizing and ki...    News   
6  Donald Trump spent a good portion of his day a...    News   
7  In the wake of yet another court decision that...    News   
8  Many people have raised the alarm regarding th...    News   
9  Just when you might have thought we d get a br...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017  
5  December 25, 2017  
6  December 23, 2017  
7  December 23, 2017  
8  December 22, 2017  
9  December 21, 2017

In [4]:
true_news.head(10)

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   
5  White House, Congress prepare for talks on spe...   
6  Trump says Russia probe will be fair, but time...   
7  Factbox: Trump on Twitter (Dec 29) - Approval ...   
8         Trump on Twitter (Dec 28) - Global Warming   
9  Alabama official to certify Senator-elect Jone...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   
5  WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...  politicsNews   
6  WEST PALM BEACH, Fla (Reuters) - President Don...  politicsNews   
7  The following statements were posted to the ve...  politicsNews   
8  The following statements were posted to the ve...  politicsNews   
9  WASHINGTON (Reuters) - Alabama Secretary of St...  politicsNews   

                 date  
0  December 31, 2017   
1  December 29, 2017   
2  December 31, 2017   
3  December 30, 2017   
4  December 29, 2017   
5  December 29, 2017   
6  December 29, 2017   
7  December 29, 2017   
8  December 29, 2017   
9  December 28, 2017

In [5]:
fake_news['class'] = 0
true_news['class'] = 1

In [6]:
fake_news.shape,true_news.shape

((23481, 5), (21417, 5))

In [7]:
fake_news.shape, true_news.shape

((23481, 5), (21417, 5))

In [8]:
marge = pd.concat([fake_news, true_news], axis =0 )
marge.head(10)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   
5  The number of cases of cops brutalizing and ki...    News   
6  Donald Trump spent a good portion of his day a...    News   
7  In the wake of yet another court decision that...    News   
8  Many people have raised the alarm regarding th...    News   
9  Just when you might have thought we d get a br...    News   

                date  class  
0  December 31, 2017      0  
1  December 31, 2017      0  
2  December 30, 2017      0  
3  December 29, 2017      0  
4  December 25, 2017      0  
5  December 25, 2017      0  
6  December 23, 2017      0  
7  December 23, 2017      0  
8  December 22, 2017      0  
9  December 21, 2017      0

In [9]:
marge.columns

Index(['title', 'text', 'subject', 'date', 'class'], dtype='object')

In [10]:
df = marge.drop(["title","subject","date"],axis=1)

In [11]:
df.isnull().sum()

text     0
class    0
dtype: int64

In [12]:
df = df.sample(frac = 1)          # Never Change this

In [13]:
df.head()

text  class
14890  LONDON (Reuters) - British Prime Minister Ther...      1
9135   (Reuters) - Detroit would sell its first gener...      1
14356  This is a brilliantly written piece by Nick Sh...      0
5130   SAN FRANCISCO/NEW YORK (Reuters) - Parents who...      1
82     WASHINGTON (Reuters) - The U.S. Senate parliam...      1

In [14]:
df.reset_index(inplace = True)
df.drop(["index"], axis = 1, inplace = True)

In [15]:
df.columns

Index(['text', 'class'], dtype='object')

In [16]:
df.head()

text  class
0  LONDON (Reuters) - British Prime Minister Ther...      1
1  (Reuters) - Detroit would sell its first gener...      1
2  This is a brilliantly written piece by Nick Sh...      0
3  SAN FRANCISCO/NEW YORK (Reuters) - Parents who...      1
4  WASHINGTON (Reuters) - The U.S. Senate parliam...      1

#### Creating a function to convert the text in lowercase, remove the extra space, special chr., ulr and links.

In [17]:
def wordopt(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub("\\W"," ",text) 
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)    
    return text

In [18]:
df["text"] = df["text"].apply(wordopt)

In [19]:
x = df["text"]
y = df["class"]

In [20]:
 x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30)

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [22]:
vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

### 1. Logistic Regression

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
LR = LogisticRegression()
LR.fit(xv_train,y_train)

LogisticRegression()

In [25]:
pred_lr=LR.predict(xv_test)

In [26]:
LR.score(xv_test, y_test)

0.98634001484781

In [27]:
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      6983
           1       0.99      0.99      0.99      6487

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470



###  Decision Tree Classification

In [28]:
from sklearn.tree import DecisionTreeClassifier

In [29]:
DT = DecisionTreeClassifier()
DT.fit(xv_train, y_train)

DecisionTreeClassifier()

In [30]:
pred_dt = DT.predict(xv_test)

In [31]:
DT.score(xv_test, y_test)

0.9944320712694877

In [32]:
print(classification_report(y_test, pred_dt))    # Precision , Recall , F-measure , Accuracy

              precision    recall  f1-score   support

           0       1.00      0.99      0.99      6983
           1       0.99      0.99      0.99      6487

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470



In [33]:
y_pred = DT.predict(xv_test)   

In [34]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))                                  #confusion Matrix

[[6942   41]
 [  34 6453]]


In [35]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))        #error
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.005567928730512249
Mean Squared Error: 0.005567928730512249
Root Mean Squared Error: 0.07461855486748754


### Naive Bayes using Bernoulli naive bayes

In [36]:
from sklearn.naive_bayes import BernoulliNB

In [37]:
BNB = BernoulliNB()

In [38]:
BNB.fit(xv_train, y_train)

BernoulliNB()

In [39]:
pred_bnb = BNB.predict(xv_test)

In [40]:
BNB.score(xv_test,y_test)

0.9432813659985152

In [41]:
print(classification_report(y_test, pred_bnb))      # Precision , Recall , F-measure , Accuracy

              precision    recall  f1-score   support

           0       0.96      0.93      0.94      6983
           1       0.93      0.96      0.94      6487

    accuracy                           0.94     13470
   macro avg       0.94      0.94      0.94     13470
weighted avg       0.94      0.94      0.94     13470



In [42]:
print(confusion_matrix(y_test, pred_bnb))                  #confusion Matrix

[[6479  504]
 [ 260 6227]]


In [43]:

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, pred_bnb))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, pred_bnb))                 #error
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, pred_bnb)))

Mean Absolute Error: 0.05671863400148478
Mean Squared Error: 0.05671863400148478
Root Mean Squared Error: 0.23815674250687252


### K nearest neighbor

In [44]:
from sklearn.neighbors import KNeighborsClassifier

In [45]:
ng = KNeighborsClassifier()
ng.fit(xv_test, y_test)

KNeighborsClassifier()

In [46]:
pred_knn = ng.predict(xv_test)

In [47]:
ng.score(xv_test,y_test)

0.6662212323682257

In [48]:
print(classification_report(y_test, pred_knn))      # Precision , Recall , F-measure , Accuracy

              precision    recall  f1-score   support

           0       0.61      0.99      0.75      6983
           1       0.96      0.32      0.48      6487

    accuracy                           0.67     13470
   macro avg       0.79      0.65      0.62     13470
weighted avg       0.78      0.67      0.62     13470



In [49]:
print(confusion_matrix(y_test, pred_knn))                  #confusion Matrix

[[6905   78]
 [4418 2069]]


In [50]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, pred_knn))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, pred_knn))                 #error
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, pred_knn)))

Mean Absolute Error: 0.33377876763177433
Mean Squared Error: 0.33377876763177433
Root Mean Squared Error: 0.5777358978216381


### Support Vector Machine  

In [51]:
from sklearn.svm import LinearSVC

In [52]:
ls = LinearSVC()

In [53]:
ls.fit(xv_test, y_test)

LinearSVC()

In [54]:
pred_ls = ls.predict(xv_test)

In [55]:
ls.score(xv_test,y_test)

0.9997030438010394

In [56]:
print(classification_report(y_test, pred_ls))      # Precision , Recall , F-measure , Accuracy

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6983
           1       1.00      1.00      1.00      6487

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470



In [57]:
print(confusion_matrix(y_test, pred_ls))                  #confusion Matrix

[[6980    3]
 [   1 6486]]


In [58]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, pred_ls))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, pred_ls))                 #error
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, pred_ls)))

Mean Absolute Error: 0.0002969561989606533
Mean Squared Error: 0.0002969561989606533
Root Mean Squared Error: 0.01723241709571392


###  ANN (Artificial Neural Network)

In [59]:
from sklearn.neural_network import MLPClassifier

In [60]:
ann = MLPClassifier()

In [61]:
ann.fit(xv_test, y_test)

MLPClassifier()

In [62]:
pred_ann = ann.predict(xv_test)

In [63]:
ann.score(xv_test,y_test)

1.0

In [64]:
print(classification_report(y_test, pred_ann))      # Precision , Recall , F-measure , Accuracy

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6983
           1       1.00      1.00      1.00      6487

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470



In [65]:
print(confusion_matrix(y_test, pred_ann))                  #confusion Matrix

[[6983    0]
 [   0 6487]]


In [66]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, pred_ann))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, pred_ann))                 #error
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, pred_ann)))

Mean Absolute Error: 0.0
Mean Squared Error: 0.0
Root Mean Squared Error: 0.0
