In [74]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn import metrics
import re
import string
from sklearn.linear_model import LogisticRegression

In [2]:
fake_news=pd.read_csv("Fake.csv")
true_news=pd.read_csv("True.csv")

In [3]:
fake_news.head(10)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   
5  The number of cases of cops brutalizing and ki...    News   
6  Donald Trump spent a good portion of his day a...    News   
7  In the wake of yet another court decision that...    News   
8  Many people have raised the alarm regarding th...    News   
9  Just when you might have thought we d get a br...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017  
5  December 25, 2017  
6  December 23, 2017  
7  December 23, 2017  
8  December 22, 2017  
9  December 21, 2017

In [4]:
true_news.head(10)

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   
5  White House, Congress prepare for talks on spe...   
6  Trump says Russia probe will be fair, but time...   
7  Factbox: Trump on Twitter (Dec 29) - Approval ...   
8         Trump on Twitter (Dec 28) - Global Warming   
9  Alabama official to certify Senator-elect Jone...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   
5  WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...  politicsNews   
6  WEST PALM BEACH, Fla (Reuters) - President Don...  politicsNews   
7  The following statements were posted to the ve...  politicsNews   
8  The following statements were posted to the ve...  politicsNews   
9  WASHINGTON (Reuters) - Alabama Secretary of St...  politicsNews   

                 date  
0  December 31, 2017   
1  December 29, 2017   
2  December 31, 2017   
3  December 30, 2017   
4  December 29, 2017   
5  December 29, 2017   
6  December 29, 2017   
7  December 29, 2017   
8  December 29, 2017   
9  December 28, 2017

In [5]:
fake_news['class'] = 0
true_news['class'] = 1

In [6]:
fake_news.shape,true_news.shape

((23481, 5), (21417, 5))

In [7]:
fake_manual_testing = fake_news.tail(10)
for i in range(23480,23470,-1):
    fake_news.drop([i], axis = 0, inplace = True)
true_manual_testing = true_news.tail(10)
for i in range(21416,21406,-1):
    true_news.drop([i], axis = 0, inplace = True)

In [8]:
fake_news.shape, true_news.shape

((23471, 5), (21407, 5))

In [9]:
fake_manual_testing["class"] = 0
true_manual_testing["class"] = 1

C:\Users\KIIT\AppData\Local\Temp/ipykernel_12228/948382439.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fake_manual_testing["class"] = 0
C:\Users\KIIT\AppData\Local\Temp/ipykernel_12228/948382439.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  true_manual_testing["class"] = 1


In [10]:
fake_manual_testing.head(5)

title  \
23471  Seven Iranians freed in the prisoner swap have...   
23472                      #Hashtag Hell & The Fake Left   
23473  Astroturfing: Journalist Reveals Brainwashing ...   
23474          The New American Century: An Era of Fraud   
23475  Hillary Clinton: ‘Israel First’ (and no peace ...   

                                                    text      subject  \
23471  21st Century Wire says This week, the historic...  Middle-east   
23472   By Dady Chery and Gilbert MercierAll writers ...  Middle-east   
23473  Vic Bishop Waking TimesOur reality is carefull...  Middle-east   
23474  Paul Craig RobertsIn the last years of the 20t...  Middle-east   
23475  Robert Fantina CounterpunchAlthough the United...  Middle-east   

                   date  class  
23471  January 20, 2016      0  
23472  January 19, 2016      0  
23473  January 19, 2016      0  
23474  January 19, 2016      0  
23475  January 18, 2016      0

In [11]:
true_manual_testing.head()

title  \
21407  Mata Pires, owner of embattled Brazil builder ...   
21408  U.S., North Korea clash at U.N. forum over nuc...   
21409  U.S., North Korea clash at U.N. arms forum on ...   
21410  Headless torso could belong to submarine journ...   
21411  North Korea shipments to Syria chemical arms a...   

                                                    text    subject  \
21407  SAO PAULO (Reuters) - Cesar Mata Pires, the ow...  worldnews   
21408  GENEVA (Reuters) - North Korea and the United ...  worldnews   
21409  GENEVA (Reuters) - North Korea and the United ...  worldnews   
21410  COPENHAGEN (Reuters) - Danish police said on T...  worldnews   
21411  UNITED NATIONS (Reuters) - Two North Korean sh...  worldnews   

                   date  class  
21407  August 22, 2017       1  
21408  August 22, 2017       1  
21409  August 22, 2017       1  
21410  August 22, 2017       1  
21411  August 21, 2017       1

In [12]:
df_manual_testing = pd.concat([fake_manual_testing,true_manual_testing], axis = 0)
df_manual_testing.to_csv("manual_testing.csv")

In [13]:
marge = pd.concat([fake_news, true_news], axis =0 )
marge.head(10)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   
5  The number of cases of cops brutalizing and ki...    News   
6  Donald Trump spent a good portion of his day a...    News   
7  In the wake of yet another court decision that...    News   
8  Many people have raised the alarm regarding th...    News   
9  Just when you might have thought we d get a br...    News   

                date  class  
0  December 31, 2017      0  
1  December 31, 2017      0  
2  December 30, 2017      0  
3  December 29, 2017      0  
4  December 25, 2017      0  
5  December 25, 2017      0  
6  December 23, 2017      0  
7  December 23, 2017      0  
8  December 22, 2017      0  
9  December 21, 2017      0

In [14]:
marge.columns

Index(['title', 'text', 'subject', 'date', 'class'], dtype='object')

In [15]:
df = marge.drop(["title","subject","date"],axis=1)

In [16]:
df.isnull().sum()

text     0
class    0
dtype: int64

In [17]:
df = df.sample(frac = 1)          # Never Change this

In [18]:
df.head()

text  class
18883  BANGKOK (Reuters) - Thailand s Supreme Court c...      1
13497  Baton Rouge became the scene of another police...      0
16867  MOGADISHU (Reuters) - A car bomb exploded outs...      1
7204   BERLIN (Reuters) - U.S. President Barack Obama...      1
16837  Are you tired of supporting companies who are ...      0

In [19]:
df.reset_index(inplace = True)
df.drop(["index"], axis = 1, inplace = True)

In [20]:
df.columns

Index(['text', 'class'], dtype='object')

In [21]:
df.head()

text  class
0  BANGKOK (Reuters) - Thailand s Supreme Court c...      1
1  Baton Rouge became the scene of another police...      0
2  MOGADISHU (Reuters) - A car bomb exploded outs...      1
3  BERLIN (Reuters) - U.S. President Barack Obama...      1
4  Are you tired of supporting companies who are ...      0

#### Creating a function to convert the text in lowercase, remove the extra space, special chr., ulr and links.

In [83]:
def wordopt(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub("\\W"," ",text) 
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text) 
    text = np.size(data[0::,1].astype(np.float))
    return text

In [23]:
df["text"] = df["text"].apply(wordopt)

In [79]:
df.head()

text  class
0  bangkok  reuters    thailand s supreme court c...      1
1  baton rouge became the scene of another police...      0
2  mogadishu  reuters    a car bomb exploded outs...      1
3  berlin  reuters    u s  president barack obama...      1
4  are you tired of supporting companies who are ...      0

In [24]:
x = df["text"]
y = df["class"]

In [25]:
 x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30)

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [27]:
vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

### 1. Logistic Regression

In [28]:
from sklearn.linear_model import LogisticRegression

In [29]:
LR = LogisticRegression()
LR.fit(xv_train,y_train)

LogisticRegression()

In [30]:
pred_lr=LR.predict(xv_test)

In [31]:
LR.score(xv_test, y_test)

0.9849227569815805

In [32]:
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      7018
           1       0.98      0.99      0.98      6446

    accuracy                           0.98     13464
   macro avg       0.98      0.99      0.98     13464
weighted avg       0.98      0.98      0.98     13464



###  Decision Tree Classification

In [33]:
from sklearn.tree import DecisionTreeClassifier

In [34]:
DT = DecisionTreeClassifier()
DT.fit(xv_train, y_train)

DecisionTreeClassifier()

In [35]:
pred_dt = DT.predict(xv_test)

In [36]:
DT.score(xv_test, y_test)

0.9959893048128342

In [37]:
print(classification_report(y_test, pred_dt))    # Precision , Recall , F-measure , Accuracy

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7018
           1       1.00      1.00      1.00      6446

    accuracy                           1.00     13464
   macro avg       1.00      1.00      1.00     13464
weighted avg       1.00      1.00      1.00     13464



In [38]:
y_pred = DT.predict(xv_test)   

In [39]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))                                  #confusion Matrix

[[6996   22]
 [  32 6414]]


In [40]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))        #error
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.004010695187165776
Mean Squared Error: 0.004010695187165776
Root Mean Squared Error: 0.06333004963811237


### Naive Bayes using Bernoulli naive bayes

In [41]:
from sklearn.naive_bayes import BernoulliNB

In [42]:
BNB = BernoulliNB()

In [43]:
BNB.fit(xv_train, y_train)

BernoulliNB()

In [44]:
pred_bnb = BNB.predict(xv_test)

In [45]:
BNB.score(xv_test,y_test)

0.9454099821746881

In [46]:
print(classification_report(y_test, pred_bnb))      # Precision , Recall , F-measure , Accuracy

              precision    recall  f1-score   support

           0       0.97      0.93      0.95      7018
           1       0.92      0.97      0.94      6446

    accuracy                           0.95     13464
   macro avg       0.95      0.95      0.95     13464
weighted avg       0.95      0.95      0.95     13464



In [47]:
print(confusion_matrix(y_test, pred_bnb))                  #confusion Matrix

[[6504  514]
 [ 221 6225]]


In [48]:

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, pred_bnb))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, pred_bnb))                 #error
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, pred_bnb)))

Mean Absolute Error: 0.05459001782531194
Mean Squared Error: 0.05459001782531194
Root Mean Squared Error: 0.2336450680526168


### K nearest neighbor

In [49]:
from sklearn.neighbors import KNeighborsClassifier

In [50]:
ng = KNeighborsClassifier()
ng.fit(xv_test, y_test)

KNeighborsClassifier()

In [51]:
pred_knn = ng.predict(xv_test)

In [52]:
ng.score(xv_test,y_test)

0.6710487225193108

In [53]:
print(classification_report(y_test, pred_knn))      # Precision , Recall , F-measure , Accuracy

              precision    recall  f1-score   support

           0       0.61      0.99      0.76      7018
           1       0.96      0.32      0.49      6446

    accuracy                           0.67     13464
   macro avg       0.79      0.66      0.62     13464
weighted avg       0.78      0.67      0.63     13464



In [54]:
print(confusion_matrix(y_test, pred_knn))                  #confusion Matrix

[[6941   77]
 [4352 2094]]


In [55]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, pred_knn))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, pred_knn))                 #error
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, pred_knn)))

Mean Absolute Error: 0.32895127748068925
Mean Squared Error: 0.32895127748068925
Root Mean Squared Error: 0.5735427425054642


### Support Vector Machine  

In [56]:
from sklearn.svm import LinearSVC

In [57]:
ls = LinearSVC()

In [58]:
ls.fit(xv_test, y_test)

LinearSVC()

In [59]:
pred_ls = ls.predict(xv_test)

In [60]:
ls.score(xv_test,y_test)

0.999554367201426

In [61]:
print(classification_report(y_test, pred_ls))      # Precision , Recall , F-measure , Accuracy

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7018
           1       1.00      1.00      1.00      6446

    accuracy                           1.00     13464
   macro avg       1.00      1.00      1.00     13464
weighted avg       1.00      1.00      1.00     13464



In [62]:
print(confusion_matrix(y_test, pred_ls))                  #confusion Matrix

[[7013    5]
 [   1 6445]]


In [63]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, pred_ls))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, pred_ls))                 #error
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, pred_ls)))

Mean Absolute Error: 0.000445632798573975
Mean Squared Error: 0.000445632798573975
Root Mean Squared Error: 0.021110016546037454


###  ANN (Artificial Neural Network)

In [64]:
from sklearn.neural_network import MLPClassifier

In [65]:
ann = MLPClassifier()

In [66]:
ann.fit(xv_test, y_test)

MLPClassifier()

In [67]:
pred_ann = ann.predict(xv_test)

In [68]:
ann.score(xv_test,y_test)

0.9999257278669044

In [69]:
print(classification_report(y_test, pred_ann))      # Precision , Recall , F-measure , Accuracy

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7018
           1       1.00      1.00      1.00      6446

    accuracy                           1.00     13464
   macro avg       1.00      1.00      1.00     13464
weighted avg       1.00      1.00      1.00     13464



In [70]:
print(confusion_matrix(y_test, pred_ann))                  #confusion Matrix

[[7018    0]
 [   1 6445]]


In [71]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, pred_ann))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, pred_ann))                 #error
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, pred_ann)))

Mean Absolute Error: 7.427213309566251e-05
Mean Squared Error: 7.427213309566251e-05
Root Mean Squared Error: 0.008618128166583652
